"""added_new_password

Revision ID: 005ff59dbcf0
Revises: 1b8154d577bf
Create Date: 2026-03-14 15:43:21.428052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005ff59dbcf0'
down_revision: Union[str, Sequence[str], None] = '1b8154d577bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_password')
    # ### end Alembic commands ###
